# Generated by Django 3.2.8 on 2021-10-20 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('on_sale', models.BooleanField(default=False)),
                ('size', models.BooleanField(blank=True, default=False, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('gender', models.CharField(choices=[('f', 'f'), ('m', 'm')], max_length=1)),
                ('image_a', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_b', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_c', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_d', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
